### ISSUE TITLE
bug: fix avg contribution calc + "NaN state" display on Manager

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1541]
**Overview**

Currently, when there are no donations, the Round Stats tab reads "NaN". It should say "N/A" for a more human-readable experience
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=1508-43896&t=OQbFbxGsR4EZ8x5g-4)

<img width="1425" alt="nan" src="https://user-images.githubusercontent.com/26017180/233487735-bb412ef7-cae5-40e8-9f7a-e70bfe73c546.png">

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/
2. Find a round that has received no donations yet 
3. Go to Round Stats tab 
4. Look at "Average Contribution" box which will read "NaN", when it should just say "N/A" 

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by meg-fsc** [comment]
Recheck if this is still an issue

**Comment by meg-fsc** [comment]
NaN should be fixed -- but check if we are showing 0 where we should be showing N/A

**Comment by michellema1208** [comment]
@meg-fsc - I'm still seeing this bug on staging - if you have a round that has not received any donations, we display "NaN" in the Average Contribution box on the Round Stats page (see below). I'm going to move this back to TODO! 

![Image](https://github.com/gitcoinco/grants-stack/assets/26017180/04f120fa-1c0f-4ccb-904e-fb185629c6b5)
